# Generated by Django 4.0.1 on 2022-01-27 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='character',
            name='icon_path',
        ),
        migrations.AddField(
            model_name='character',
            name='type_character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.typecharacter'),
        ),
        migrations.AddField(
            model_name='typecharacter',
            name='icon_path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
