# Generated by Django 4.0.1 on 2022-01-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_character_damage_remove_character_icon_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
